ci: fix publish-dockerhub (DAEMONS)
Commit 82b9ba16, part of #816, broke upload of all DAEMONS but
base. The reason why it wasn't detected is because composite action
leaves DAEMONS set, so step 3 passes and step 4 just uploads
the single daemon base.

Fix it by defining it globally, and add a check for the list of
DAEMONS as part of step2, so that this is not happening again.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -7,6 +7,9 @@ on:
     - cron: '0 0 * * *'  # every day at midnight
 
 #Global vars
+env:
+  DAEMONS: "pmacctd nfacctd sfacctd uacctd pmbgpd pmbmpd pmtelemetryd"
+
 jobs:
   ### Step 1: build container images
   builder-docker:
@@ -114,8 +117,19 @@ jobs:
           fetch-depth: 0
           fetch-tags: 1
 
+      - name: Check DAEMONS env. variable...
+        run: |
+          #Sanity, avoid regression #816
+          N_DAEMONS="$(echo $DAEMONS | wc --words)"
+          if [[ "${N_DAEMONS}" != "7" ]]; then
+              echo "ERROR: invalid number of DAEMONS: ${N_DAEMONS}"
+              exit 1
+          fi
+
       - name: Build containers
         uses: ./pmacct/.github/actions/build_containers/
+        with:
+            daemons: ${{env.DAEMONS}}
 
       - name: Docker save images
         run: |
